### ISSUE TITLE
Unexpected token ''export''

### ISSUE THREAD

**Issue by omninando** [davegomez/tree-parser#1]
Hi,

When I require this library using its latest version, node(5.x.x) responds with the following stack error:

```
~/tree-parser/helpers/includes.js:9
export default (list: Array<any>, elem: any): boolean =>
^^^^^^

SyntaxError: Unexpected token export
```

Previous versions of node prints a similar error mentioning an `unexpected reserved word` message. This is probably something related with _babel_ not transpiling the `includes.js` file. 

Other versions of this library doesn't have this problem.

**Comment by jmpas** [comment]
Same here :+1: 

Maybe changing [this line](https://github.com/davegomez/tree-parser/blob/master/package.json#L7) to compile the `helpers` folder too could solve this, I think
